language: python

# TODO re-add PyPy when they get >=3.6 support.
matrix:
  include:
    - os: linux
      dist: xenial
      python: "3.6"
      env: "VERSION=3.6"
    - os: linux
      dist: xenial
      python: "3.7"
      env: "VERSION=3.7"
    - os: linux
      dist: xenial
      python: "nightly"
      env: "VERSION=nightly"
  allow_failures:
    - env: "VERSION=nightly"

install:
  - pip install .
  - pip install coveralls
  - pip install mypy

script:
  - |
    mypy \
    botskeleton \
    --ignore-missing-imports \
    --follow-imports=skip \
    --disallow-untyped-defs \
    --incremental \
    --warn-no-return \
    --show-column-numbers

  - coverage run --source=botskeleton setup.py pytest
  - coverage report -m

after_success:
  - coveralls
