language: python

os:
    - linux

# TODO re-add PyPy when they get >=3.5 support.
python:
    - "3.6"
    - "3.7"
    - "nightly"

matrix:
    allow_failures:
        - python:
          - "3.7"
          - "nightly"

install:
    - pip install .
    - pip install coveralls
    - pip install -U git+git://github.com/python/mypy.git

script:
    - |
      mypy \
      botskeleton \
      --ignore-missing-imports --follow-imports=skip \
      --disallow-untyped-defs --incremental --warn-no-return --show-column-numbers

    - coverage run --source=botskeleton setup.py test
    - coverage report -m

after_success:
    - coveralls
